import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET(
  _request: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id: projectId } = await context.params;

    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
      select: {
        id: true,
        github_connected: true,
        github_username: true,
      },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const project = await prisma.project.findFirst({
      where: { id: projectId, user_id: user.id },
      select: {
        id: true,
        app_name: true,
        app_description: true,
      },
    });

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    // Check GitHub is connected
    if (!user.github_connected || !user.github_username) {
      return NextResponse.json(
        {
          error: "GitHub not connected",
          needsGitHub: true,
          message: "You must push to GitHub before deploying to Vercel.",
        },
        { status: 403 }
      );
    }

    // Build the repo name the same way the push API does
    const repoName = (project.app_name || "my-app")
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "") || "my-app";

    const repoFullName = `${user.github_username}/${repoName}`;
    const repoUrl = `https://github.com/${repoFullName}`;

    // Build the Vercel one-click deploy URL
    const projectName = repoName;
    const description = encodeURIComponent(
      project.app_description || `${project.app_name} — Generated by App Builder Studio`
    );

    const vercelDeployUrl =
      `https://vercel.com/new/clone` +
      `?repository-url=${encodeURIComponent(repoUrl)}` +
      `&project-name=${encodeURIComponent(projectName)}` +
      `&repository-name=${encodeURIComponent(repoName)}`;

    return NextResponse.json({
      success: true,
      vercelDeployUrl,
      repoUrl,
      repoName: repoFullName,
      projectName,
    });
  } catch (error) {
    console.error("Deploy URL error:", error);
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Failed to generate deploy URL",
      },
      { status: 500 }
    );
  }
}

// POST: Save the live URL after user deploys
export async function POST(
  request: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id: projectId } = await context.params;
    const { liveUrl } = await request.json();

    if (!liveUrl) {
      return NextResponse.json(
        { error: "No live URL provided" },
        { status: 400 }
      );
    }

    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
      select: { id: true },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const project = await prisma.project.findFirst({
      where: { id: projectId, user_id: user.id },
      select: { id: true },
    });

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    // Save the live URL to the project status
    await prisma.project.update({
      where: { id: projectId },
      data: { status: "LAUNCHED" },
    });

    return NextResponse.json({ success: true, liveUrl });
  } catch (error) {
    console.error("Save deploy URL error:", error);
    return NextResponse.json(
      { error: "Failed to save live URL" },
      { status: 500 }
    );
  }
}