import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    // FIX: Await the params (Next.js 15+ requirement)
    const { id } = await params;

    const project = await prisma.project.findUnique({
      where: { id, user_id: user.id },
      include: {
        routes: { orderBy: { sort_order: "asc" } },
        features: true,
        databaseTables: true,
      },
    });

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    // Build the Game Plan
    const gamePlan = `
S2KDOTZA GAME PLAN
==================

APP NAME: ${project.app_name || "Untitled"}
PURPOSE: ${project.app_description || "No description"}
TARGET USERS: ${project.target_users || "General audience"}

---

ROUTES (Pages):
${project.routes.map(r => `- ${r.page_name} (${r.route_path}): ${r.purpose}`).join("\n")}

---

CORE FEATURES:
${project.features.map(f => `- ${f.feature_name}`).join("\n")}

---

DATABASE STRUCTURE:
${project.databaseTables.map(t => `- ${t.table_name}: ${t.purpose}`).join("\n")}

---

BUSINESS MODEL: ${project.business_model || "Not specified"}

---
Generated by S2KDOTZA App Builder Studio
`.trim();

    return NextResponse.json({ gamePlan });
  } catch (error: any) {
    console.error("Export error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}