import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function POST(
  _request: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id: projectId } = await context.params;

    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    if (!user.github_connected || !user.github_token) {
      return NextResponse.json(
        {
          error: "GitHub not connected",
          needsConnection: true,
          connectUrl: `/api/auth/github?projectId=${projectId}`,
        },
        { status: 403 }
      );
    }

    const project = await prisma.project.findFirst({
      where: { id: projectId, user_id: user.id },
      include: {
        files: { orderBy: { file_path: "asc" } },
      },
    });

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    if (project.files.length === 0) {
      return NextResponse.json(
        { error: "No files generated yet. Generate code first." },
        { status: 400 }
      );
    }

    const token = user.github_token;
    const username = user.github_username;

    // Create a safe repository name
    const repoName = (project.app_name || "my-app")
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "") || "my-app";

    // Check if repo already exists
    const checkRepo = await fetch(
      `https://api.github.com/repos/${username}/${repoName}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github.v3+json",
        },
      }
    );

    let repoFullName: string;
    let repoUrl: string;
    let isNew = false;

    if (checkRepo.status === 404) {
      // Create the repository
      const createRepo = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: repoName,
          description: project.app_description || `${project.app_name} — Generated by App Builder Studio by S2KDOTZA`,
          private: false,
          auto_init: false,
        }),
      });

      if (!createRepo.ok) {
        const err = await createRepo.json();
        return NextResponse.json(
          { error: `Failed to create repository: ${err.message}` },
          { status: 500 }
        );
      }

      const repoData = await createRepo.json();
      repoFullName = repoData.full_name;
      repoUrl = repoData.html_url;
      isNew = true;
    } else {
      const repoData = await checkRepo.json();
      repoFullName = repoData.full_name;
      repoUrl = repoData.html_url;
    }

    // Push all files to the repository
    const results = {
      pushed: 0,
      failed: 0,
      errors: [] as string[],
    };

    for (const file of project.files) {
      try {
        // Check if file already exists to get its SHA for updates
        let fileSha: string | undefined;

        const existingFile = await fetch(
          `https://api.github.com/repos/${repoFullName}/contents/${file.file_path}`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
              Accept: "application/vnd.github.v3+json",
            },
          }
        );

        if (existingFile.ok) {
          const existingData = await existingFile.json();
          fileSha = existingData.sha;
        }

        // Convert content to base64
        const contentBase64 = Buffer.from(file.content, "utf-8").toString("base64");

        // Push or update the file
        const pushFile = await fetch(
          `https://api.github.com/repos/${repoFullName}/contents/${file.file_path}`,
          {
            method: "PUT",
            headers: {
              Authorization: `Bearer ${token}`,
              Accept: "application/vnd.github.v3+json",
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              message: isNew
                ? `Initial commit: ${file.file_path}`
                : `Update: ${file.file_path}`,
              content: contentBase64,
              ...(fileSha ? { sha: fileSha } : {}),
            }),
          }
        );

        if (pushFile.ok) {
          results.pushed++;
        } else {
          results.failed++;
          results.errors.push(file.file_path);
        }
      } catch (fileError) {
        results.failed++;
        results.errors.push(file.file_path);
      }
    }

    // Also add boilerplate files
    const boilerplateFiles = [
      {
        path: "README.md",
        content: `# ${project.app_name}\n\n${project.app_description || ""}\n\n## Generated by App Builder Studio\n\nby S2KDOTZA Entertainment\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
      },
      {
        path: ".gitignore",
        content: `node_modules\n.next\n.env\n.env.local\n.env.*.local\ndist\nbuild\n`,
      },
    ];

    for (const bf of boilerplateFiles) {
      try {
        const existingFile = await fetch(
          `https://api.github.com/repos/${repoFullName}/contents/${bf.path}`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
              Accept: "application/vnd.github.v3+json",
            },
          }
        );

        let fileSha: string | undefined;
        if (existingFile.ok) {
          const ed = await existingFile.json();
          fileSha = ed.sha;
        }

        await fetch(
          `https://api.github.com/repos/${repoFullName}/contents/${bf.path}`,
          {
            method: "PUT",
            headers: {
              Authorization: `Bearer ${token}`,
              Accept: "application/vnd.github.v3+json",
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              message: `Add ${bf.path}`,
              content: Buffer.from(bf.content, "utf-8").toString("base64"),
              ...(fileSha ? { sha: fileSha } : {}),
            }),
          }
        );
      } catch {
        // Boilerplate files are non-critical
      }
    }

    return NextResponse.json({
      success: true,
      repoUrl,
      repoName: repoFullName,
      filespushed: results.pushed,
      filesFailed: results.failed,
      isNew,
    });
  } catch (error) {
    console.error("GitHub push error:", error);
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Failed to push to GitHub",
      },
      { status: 500 }
    );
  }
}

// GET: Check GitHub connection status
export async function GET(
  _request: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
      select: {
        github_connected: true,
        github_username: true,
      },
    });

    return NextResponse.json({
      connected: user?.github_connected || false,
      username: user?.github_username || null,
    });
  } catch (error) {
    return NextResponse.json({ error: "Failed to check status" }, { status: 500 });
  }
}