// Converts project data into self-contained, interactive HTML screens.
// Uses data-nav attributes and a global click listener for safe iframe navigation.

interface PreviewInput {
  appName: string;
  appDescription: string;
  routes: Array<{ page_name: string; route_path: string; purpose: string | null }>;
  features: Array<{ feature_name: string; priority: string | null }>;
  databaseTables: Array<{ table_name: string; purpose: string | null }>;
}

export function generatePreviewHTML(
  input: PreviewInput,
  currentPath: string = "/"
): string {
  const normalizedPath = currentPath.startsWith("/")
    ? currentPath
    : `/${currentPath}`;

  const navLinks = input.routes
    .filter((r) => r.route_path !== "/")
    .slice(0, 4)
    .map(
      (r) =>
        `<a data-nav="${encodeURIComponent(r.route_path)}" class="px-3 py-2 rounded-lg text-sm font-medium ${
          normalizedPath === r.route_path
            ? "bg-slate-800 text-white"
            : "text-slate-300 hover:text-white hover:bg-slate-800/50"
        } transition cursor-pointer">${escapeHtml(r.page_name)}</a>`
    )
    .join("\n");

  const header = `
    <nav class="border-b border-slate-800 bg-slate-900 px-6 py-4">
      <div class="max-w-6xl mx-auto flex items-center justify-between">
        <a data-nav="%2F" class="text-xl font-bold text-white flex items-center gap-2 cursor-pointer">
          <span class="text-orange-500">⚡</span> ${escapeHtml(input.appName)}
        </a>
        <div class="flex items-center gap-2">
          ${navLinks}
        </div>
      </div>
    </nav>
  `;

  const footer = `
    <footer class="border-t border-slate-800 bg-slate-950 py-8 text-center text-slate-500 text-xs mt-auto">
      <p>© ${new Date().getFullYear()} ${escapeHtml(input.appName)} — Generated by S2KDOTZA App Builder Studio.</p>
    </footer>
  `;

  // Global navigation script - included in every screen
  const navScript = `
    <script>
      document.addEventListener('click', function(e) {
        const target = e.target.closest('[data-nav]');
        if (target) {
          e.preventDefault();
          const path = target.getAttribute('data-nav');
          window.location.href = '?path=' + path;
        }
      });
    </script>
  `;

  let bodyContent = "";
  let isAuthScreen = false;

  switch (normalizedPath) {
    case "/":
      bodyContent = renderHomeScreen(input);
      break;
    case "/auth":
    case "/login":
    case "/signup":
      bodyContent = renderAuthScreen(input);
      isAuthScreen = true;
      break;
    case "/dashboard":
      bodyContent = renderDashboardScreen(input);
      break;
    case "/settings":
      bodyContent = renderSettingsScreen(input);
      break;
    default:
      bodyContent = renderGenericScreen(input, normalizedPath);
      break;
  }

  if (isAuthScreen) {
    // Auth screen is self-contained
    return bodyContent;
  }

  return `<!DOCTYPE html>
<html lang="en" class="h-full">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(input.appName)} - Preview</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-white flex flex-col min-h-full font-sans antialiased">
  ${header}
  <div class="flex-1 flex flex-col">
    ${bodyContent}
  </div>
  ${footer}
  ${navScript}
</body>
</html>`;
}

function renderHomeScreen(input: PreviewInput): string {
  const featureCards = input.features
    .slice(0, 6)
    .map(
      (f) => `
      <div class="p-6 rounded-2xl bg-slate-900 border border-slate-800 hover:border-orange-500/50 transition duration-300">
        <div class="w-10 h-10 rounded-lg bg-orange-600/20 text-orange-400 mb-4 flex items-center justify-center font-bold">✓</div>
        <h3 class="text-lg font-bold text-white mb-2">${escapeHtml(f.feature_name)}</h3>
        <p class="text-slate-400 text-sm">Enterprise-grade implementation ready.</p>
      </div>`
    )
    .join("\n");

  return `
    <section class="max-w-5xl mx-auto px-6 py-20 text-center">
      <h1 class="text-6xl font-extrabold mb-6 tracking-tight bg-gradient-to-b from-white to-slate-400 bg-clip-text text-transparent">
        ${escapeHtml(input.appName)}
      </h1>
      <p class="text-lg text-slate-400 mb-10 max-w-2xl mx-auto leading-relaxed">
        ${escapeHtml(input.appDescription)}
      </p>
      <div class="flex gap-4 justify-center">
        <a data-nav="%2Fauth" class="rounded-xl bg-orange-600 hover:bg-orange-500 px-8 py-4 font-semibold transition shadow-lg shadow-orange-600/20 cursor-pointer">
          Get Started Free
        </a>
        <a data-nav="%2Fdashboard" class="rounded-xl border border-slate-800 hover:bg-slate-900 px-8 py-4 font-semibold transition cursor-pointer">
          View Demo Dashboard
        </a>
      </div>
    </section>

    <section class="max-w-5xl mx-auto px-6 py-12 border-t border-slate-900 w-full">
      <h2 class="text-3xl font-bold mb-8 text-center">System Capabilities</h2>
      <div class="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
        ${featureCards}
      </div>
    </section>
  `;
}

function renderAuthScreen(input: PreviewInput): string {
  return `<!DOCTYPE html>
<html lang="en" class="h-full">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sign In - ${escapeHtml(input.appName)}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-white flex items-center justify-center min-h-full font-sans p-6">
  <div class="w-full max-w-md rounded-2xl bg-slate-900 border border-slate-800 p-8 shadow-2xl">
    <div class="text-center mb-6">
      <a data-nav="%2F" class="text-xs text-orange-500 hover:text-orange-400 cursor-pointer">&larr; Back to Home</a>
      <h1 class="text-3xl font-bold mt-4">${escapeHtml(input.appName)}</h1>
      <p class="text-slate-400 text-sm mt-2">Sign in to manage your account</p>
    </div>

    <form class="space-y-4 mt-6" data-form-nav="%2Fdashboard">
      <div>
        <label class="block text-xs font-semibold text-slate-400 uppercase">Email Address</label>
        <input type="email" required placeholder="name@company.com" class="mt-1.5 w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-orange-500" />
      </div>
      <div>
        <label class="block text-xs font-semibold text-slate-400 uppercase">Password</label>
        <input type="password" required placeholder="••••••••" class="mt-1.5 w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-orange-500" />
      </div>
      <button type="submit" class="w-full rounded-xl bg-orange-600 hover:bg-orange-500 py-3 text-sm font-semibold transition mt-2 cursor-pointer">
        Sign In
      </button>
    </form>

    <div class="relative flex py-5 items-center">
      <div class="flex-grow border-t border-slate-800"></div>
      <span class="flex-shrink mx-4 text-slate-500 text-xs uppercase">or</span>
      <div class="flex-grow border-t border-slate-800"></div>
    </div>

    <a data-nav="%2Fdashboard" class="w-full rounded-xl border border-slate-800 hover:bg-slate-800/40 py-3 text-sm font-semibold transition flex items-center justify-center gap-2 cursor-pointer block text-center">
      Continue with Google
    </a>
  </div>
  <script>
    document.addEventListener('click', function(e) {
      const target = e.target.closest('[data-nav]');
      if (target) {
        e.preventDefault();
        const path = target.getAttribute('data-nav');
        window.location.href = '?path=' + path;
      }
    });
    document.addEventListener('submit', function(e) {
      const form = e.target.closest('[data-form-nav]');
      if (form) {
        e.preventDefault();
        const path = form.getAttribute('data-form-nav');
        window.location.href = '?path=' + path;
      }
    });
  </script>
</body>
</html>`;
}

function renderDashboardScreen(input: PreviewInput): string {
  const tableRows = input.databaseTables
    .map(
      (t) => `
    <tr class="border-b border-slate-800 hover:bg-slate-900/30">
      <td class="px-6 py-4 font-mono text-sm text-emerald-400">${escapeHtml(t.table_name)}</td>
      <td class="px-6 py-4 text-sm text-slate-300">${escapeHtml(t.purpose || "Database storage entity")}</td>
      <td class="px-6 py-4 text-xs text-slate-500">Active</td>
    </tr>`
    )
    .join("\n");

  return `
    <div class="max-w-6xl w-full mx-auto px-6 py-10 flex-1">
      <div class="flex justify-between items-center mb-8">
        <div>
          <h1 class="text-3xl font-bold">App Dashboard</h1>
          <p class="text-sm text-slate-400 mt-1">Live metrics and database models for ${escapeHtml(input.appName)}</p>
        </div>
        <a data-nav="%2Fsettings" class="rounded-lg bg-slate-900 border border-slate-800 px-4 py-2 text-sm font-medium hover:bg-slate-800 cursor-pointer">
          ⚙️ Settings
        </a>
      </div>

      <div class="grid gap-4 md:grid-cols-3 mb-8">
        <div class="p-6 bg-slate-900 border border-slate-800 rounded-xl">
          <p class="text-xs text-slate-500 uppercase font-semibold">Total Pages</p>
          <p class="text-3xl font-bold mt-2">${input.routes.length}</p>
        </div>
        <div class="p-6 bg-slate-900 border border-slate-800 rounded-xl">
          <p class="text-xs text-slate-500 uppercase font-semibold">Configured Features</p>
          <p class="text-3xl font-bold mt-2">${input.features.length}</p>
        </div>
        <div class="p-6 bg-slate-900 border border-slate-800 rounded-xl">
          <p class="text-xs text-slate-500 uppercase font-semibold">Database Tables</p>
          <p class="text-3xl font-bold mt-2">${input.databaseTables.length}</p>
        </div>
      </div>

      <div class="rounded-xl border border-slate-800 bg-slate-900 overflow-hidden">
        <div class="p-5 border-b border-slate-800 bg-slate-950">
          <h3 class="font-bold text-white text-lg">System Database Schemas</h3>
        </div>
        <div class="overflow-x-auto">
          <table class="w-full text-left border-collapse">
            <thead>
              <tr class="bg-slate-950/40 border-b border-slate-800 text-slate-400 text-xs font-bold uppercase">
                <th class="px-6 py-3">Table Name</th>
                <th class="px-6 py-3">Purpose</th>
                <th class="px-6 py-3">Status</th>
              </tr>
            </thead>
            <tbody>
              ${tableRows || `<tr><td colspan="3" class="px-6 py-8 text-center text-slate-500">No database tables defined yet.</td></tr>`}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `;
}

function renderSettingsScreen(input: PreviewInput): string {
  return `
    <div class="max-w-3xl w-full mx-auto px-6 py-10 flex-1">
      <h1 class="text-3xl font-bold mb-2">Application Settings</h1>
      <p class="text-sm text-slate-400 mb-8">Manage specifications and options for ${escapeHtml(input.appName)}</p>

      <div class="space-y-6">
        <div class="p-6 bg-slate-900 border border-slate-800 rounded-xl">
          <h3 class="font-bold text-lg mb-4 text-orange-400">General Information</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-xs text-slate-400 uppercase font-semibold">Application Name</label>
              <input type="text" readonly value="${escapeHtml(input.appName)}" class="mt-1.5 w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-sm text-slate-400 cursor-not-allowed" />
            </div>
            <div>
              <label class="block text-xs text-slate-400 uppercase font-semibold">Purpose Description</label>
              <textarea readonly class="mt-1.5 w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-sm text-slate-400 cursor-not-allowed resize-none" rows="3">${escapeHtml(input.appDescription)}</textarea>
            </div>
          </div>
        </div>

        <div class="p-6 bg-slate-900 border border-slate-800 rounded-xl">
          <h3 class="font-bold text-lg mb-2 text-orange-400">Development Environment</h3>
          <p class="text-xs text-slate-400 mb-4">Stage 2: Code Generation active inside The Forge.</p>
          <div class="flex justify-between items-center py-2 border-b border-slate-800">
            <span class="text-sm">Prisma ORM Client</span>
            <span class="text-xs bg-emerald-950 text-emerald-400 border border-emerald-800 px-2 py-0.5 rounded font-mono">v6.19.3</span>
          </div>
          <div class="flex justify-between items-center py-2 border-b border-slate-800">
            <span class="text-sm">Next.js Framework</span>
            <span class="text-xs bg-emerald-950 text-emerald-400 border border-emerald-800 px-2 py-0.5 rounded font-mono">v16.2.10</span>
          </div>
          <div class="flex justify-between items-center py-2">
            <span class="text-sm">Auth.js / NextAuth</span>
            <span class="text-xs bg-emerald-950 text-emerald-400 border border-emerald-800 px-2 py-0.5 rounded font-mono">Enabled</span>
          </div>
        </div>
      </div>
    </div>
  `;
}

function renderGenericScreen(input: PreviewInput, path: string): string {
  const currentRoute = input.routes.find((r) => r.route_path === path);
  const title = currentRoute ? currentRoute.page_name : "Custom Page";
  const desc = currentRoute ? currentRoute.purpose : `Content route: ${path}`;

  return `
    <div class="max-w-4xl w-full mx-auto px-6 py-20 flex-1 flex flex-col items-center justify-center text-center">
      <div class="w-16 h-16 rounded-full bg-slate-900 border border-slate-800 flex items-center justify-center text-2xl mb-6">📂</div>
      <h1 class="text-4xl font-bold mb-4">${escapeHtml(title)}</h1>
      <p class="text-lg text-slate-400 max-w-xl leading-relaxed mb-8">
        ${escapeHtml(desc || "This custom route has been planned and generated successfully.")}
      </p>
      <div class="p-6 bg-slate-900 border border-slate-800 rounded-xl max-w-md w-full font-mono text-left text-xs text-slate-400">
        <p class="text-orange-400 font-bold mb-2">// Route Configuration</p>
        <p>Route Path: <span class="text-white">${escapeHtml(path)}</span></p>
        <p>Access Level: <span class="text-white">Registered User</span></p>
        <p>File Location: <span class="text-white">app${escapeHtml(path)}/page.tsx</span></p>
      </div>
    </div>
  `;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}